## Cleaning the Adobo transactions dataset

Correct problematic data entries using the pandas operations in `D2N1_Pandas_Data_Processing.ipynb`

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os
os.chdir('/content/drive/MyDrive/DSF/DSF')

# 1. Read csv

In [ ]:
df = pd.read_csv('Data/cc_dirty.csv')
df

,cc_num,gender,city,city_pop,job,dob,acct_num,acct_num2,trans_num,unix_time,category,amt
0,6.760000e+11,M,Dasmarinas,"659,019 people",Chartered loss adjuster,12/12/1958,798000000000,798000000000,a72eaa86b043eed95b25bbb25b3153a1,1581314011,shopping_net,$68.88
1,3.520000e+15,M,Digos,"169,393 people","Administrator, charities/voluntary organisations",31/08/1970,968000000000,968000000000,060d12f91c13871a13963041736a4702,1590902968,entertainment,$50.06
2,4.140000e+18,Male,Calapan,"133,893 people",Financial controller,23/07/1953,628000000000,628000000000,18aafb6098ab0923886c0ac83592ef8d,1585461157,food_dining,$105.44
3,4.870000e+15,M,San Fernando,"121,812 people",NaN,18/07/1964,863000000000,863000000000,45bbe714e51ab8a375454d39a190b0cb,1613063704,food_dining,$38.61
4,4.720000e+15,M,Laoag,"111,125 people",Dance movement psychotherapist,11/01/1954,257000000000,257000000000,c20ee88b451f637bc6893b7460e9fee0,1601282159,gas_transport,$82.69
...,...,...,...,...,...,...,...,...,...,...,...,...
111872,4.620000e+15,M,San Fernando,"121,812 people",Personnel officer,20/11/1934,555000000000,555000000000,6ced184c93e66028e8d235ad3060de90,1625341374,personal_care,$31.37
111873,3.710000e+14,F,Maasin,"85,560 people",NaN,18/04/1966,994000000000,994000000000,0d1facd7a2af816a6fbb404a8ad6d77a,1630115183,grocery_pos,$83.14
111874,4.430000e+15,M,General Santos,"594,446 people",NaN,26/06/1960,319000000000,319000000000,599d3eec9b385473aa3791b620691416,1636919758,home,$74.76
111875,3.800000e+13,M,City of Isabela,"112,788 people",Sport and exercise psychologist,04/03/1967,378000000000,378000000000,67f47400873e964e10e029050dbe1fee,1605863062,shopping_pos,$3.27
111876,4.140000e+18,Male,Calapan,"133,893 people",Financial controller,23/07/1953,628000000000,628000000000,17f64caa57245f21fb86f04788af0296,1592849225,kids_pets,$63.80

# 2. View unique entries in each column

In [ ]:
df.columns

Index(['cc_num', 'gender', 'city', 'city_pop', 'job', 'dob', 'acct_num',
       'acct_num2', 'trans_num', 'unix_time', 'category', 'amt'],
      dtype='object')

In [ ]:
df.nunique()

cc_num           69
gender            4
city             59
city_pop         60
job              90
dob              93
acct_num         89
acct_num2        89
trans_num    100000
unix_time     99881
category         14
amt           19963
dtype: int64

In [ ]:
df['job'].unique()

array(['Chartered loss adjuster',
       'Administrator, charities/voluntary organisations',
       'Financial controller', nan, 'Dance movement psychotherapist',
       'Engineer, water', 'Education officer, museum',
       'Manufacturing systems engineer', 'Brewing technologist',
       'Tourist information centre manager', 'Seismic interpreter',
       'Customer service manager', 'Radiographer, diagnostic',
       'Diplomatic Services operational officer', 'Broadcast journalist',
       'Social worker', 'English as a foreign language teacher',
       'Emergency planning/management officer',
       'Designer, fashion/clothing', 'Contracting civil engineer',
       'Engineer, mining', 'Teacher, early years/pre',
       'Geologist, engineering', 'Psychotherapist',
       'Scientific laboratory technician', 'Aid worker',
       'Camera operator', 'Secretary, company',
       'Public relations account executive', 'Medical physicist',
       'Copywriter, advertising', 'Research officer, political party',
       'IT sales professional', 'Insurance broker',
       'Research scientist (medical)', 'Prison officer',
       'Surveyor, planning and development', 'Management consultant',
       'Land', 'Accountant, chartered certified',
       'Teacher, special educational needs',
       'Clinical scientist, histocompatibility and immunogenetics',
       'Contractor', 'Programmer, applications', 'Personnel officer',
       'Operational investment banker', 'Industrial/product designer',
       'Technical author', 'Engineering geologist', 'Office manager',
       'Sport and exercise psychologist', 'Engineer, site',
       'Outdoor activities/education manager', 'Physicist, medical',
       'Art therapist', 'Administrator, education', 'Designer, furniture',
       'Drilling engineer', 'Hotel manager', 'Database administrator',
       'Equality and diversity officer', 'Web designer',
       'Recycling officer', 'Surveyor, quantity', 'Exercise physiologist',
       'Wellsite geologist', 'Learning mentor',
       'Regulatory affairs officer', 'General practice doctor',
       'Osteopath', 'Colour technologist',
       'Sound technician, broadcasting/film/video', 'Archivist',
       'Quantity surveyor', 'Software engineer', 'Oncologist',
       'Designer, exhibition/display', 'Secondary school teacher',
       'Call centre manager', 'Psychologist, occupational',
       'Development worker, community', 'Community development worker',
       'Chemist, analytical', 'Air traffic controller',
       'Librarian, public', 'Biomedical scientist',
       'Claims inspector/assessor', 'Land/geomatics surveyor',
       'Interpreter', 'Youth worker', 'Air cabin crew'], dtype=object)

In [ ]:
df['gender'].unique()

array(['M', 'Male', 'F', 'Female'], dtype=object)

In [ ]:
df['city'].unique()

array(['Dasmarinas', 'Digos', 'Calapan', 'San Fernando', 'Laoag',
       'City of Paranaque', 'Balanga', 'Masbate', 'Malaybalay',
       'Antipolo', 'General Santos', 'Navotas', 'Marikina City',
       'Malabon', 'Palayan City', 'Naga City', 'Binan', 'Vigan', 'Mati',
       'Cadiz', 'Tacloban', 'Dagupan City', 'City of Isabela',
       'Cebu City', 'Batangas', 'Meycauayan', 'Muntinlupa City',
       'Olongapo', 'Sorsogon', 'Makati City', 'Angeles City',
       'City of Calamba', 'Pagadian', 'Tagbilaran City', 'Dumaguete City',
       'Santa Rosa', 'Butuan', 'San Pedro', 'Tuguegarao', 'Valenzuela',
       'Cabanatuan City', 'Maasin', 'Santiago', 'Manila', 'Lipa City',
       'Puerto Princesa', 'Caloocan City', 'San Jose del Monte', 'Imus',
       'San Juan', 'Dipolog', 'Legazpi City', 'Surigao', 'Iligan',
       'Talisay', 'Bacolod', 'Mandaluyong City', 'Iloilo', 'Lucena'],
      dtype=object)

In [ ]:
df['category'].unique()

array(['shopping_net', 'entertainment', 'food_dining', 'gas_transport',
       'home', 'kids_pets', nan, 'personal_care', 'shopping_pos',
       'grocery_pos', 'travel', 'misc_net', 'health_fitness', 'misc_pos',
       'grocery_net'], dtype=object)

# 3. Make a tally for each unique value in each column

In [ ]:
df['cc_num'].value_counts()

cc_num
1.800000e+14    7134
3.520000e+15    6283
3.030000e+13    3948
6.550000e+15    3184
6.390000e+11    3162
                ...
4.540000e+15      10
3.550000e+15       9
2.300000e+15       8
4.860000e+12       7
4.670000e+15       7
Name: count, Length: 69, dtype: int64

# 4. Count NaNs (if any) in each column

In [ ]:
df.isna().sum()

cc_num          0
gender          0
city            0
city_pop        0
job          8450
dob             0
acct_num        0
acct_num2       0
trans_num       0
unix_time       0
category     8559
amt             0
dtype: int64

# 5. Check if there are duplicated rows and keep only the first instance

In [ ]:
df.duplicated().sum()

11877

In [ ]:
df = df.drop_duplicates()
df

,cc_num,gender,city,city_pop,job,dob,acct_num,acct_num2,trans_num,unix_time,category,amt
0,6.760000e+11,M,Dasmarinas,"659,019 people",Chartered loss adjuster,12/12/1958,798000000000,798000000000,a72eaa86b043eed95b25bbb25b3153a1,1581314011,shopping_net,$68.88
1,3.520000e+15,M,Digos,"169,393 people","Administrator, charities/voluntary organisations",31/08/1970,968000000000,968000000000,060d12f91c13871a13963041736a4702,1590902968,entertainment,$50.06
2,4.140000e+18,Male,Calapan,"133,893 people",Financial controller,23/07/1953,628000000000,628000000000,18aafb6098ab0923886c0ac83592ef8d,1585461157,food_dining,$105.44
3,4.870000e+15,M,San Fernando,"121,812 people",NaN,18/07/1964,863000000000,863000000000,45bbe714e51ab8a375454d39a190b0cb,1613063704,food_dining,$38.61
4,4.720000e+15,M,Laoag,"111,125 people",Dance movement psychotherapist,11/01/1954,257000000000,257000000000,c20ee88b451f637bc6893b7460e9fee0,1601282159,gas_transport,$82.69
...,...,...,...,...,...,...,...,...,...,...,...,...
111870,2.470000e+15,Male,San Fernando,"306,659 people","Surveyor, quantity",01/11/1935,581000000000,581000000000,d44f411eabd406a76a60546e723a98fd,1628185569,kids_pets,$98.23
111871,3.520000e+15,M,Masbate,"95,389 people",Wellsite geologist,20/11/1967,531000000000,531000000000,7e767a74cae901c13f1a9d1d37aa63d4,1621481285,grocery_pos,$78.79
111872,4.620000e+15,M,San Fernando,"121,812 people",Personnel officer,20/11/1934,555000000000,555000000000,6ced184c93e66028e8d235ad3060de90,1625341374,personal_care,$31.37
111874,4.430000e+15,M,General Santos,"594,446 people",NaN,26/06/1960,319000000000,319000000000,599d3eec9b385473aa3791b620691416,1636919758,home,$74.76
111875,3.800000e+13,M,City of Isabela,"112,788 people",Sport and exercise psychologist,04/03/1967,378000000000,378000000000,67f47400873e964e10e029050dbe1fee,1605863062,shopping_pos,$3.27

In [ ]:
df.duplicated().sum()

0

# 6. Replace 'Male' and 'Female' in `gender` by 'M' and 'F'

In [ ]:
df['gender'] = df['gender'].replace('Male', 'M').replace('Female', 'F')
df

<ipython-input-136-caaac08c51a7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender'] = df['gender'].replace('Male', 'M').replace('Female', 'F')

,cc_num,gender,city,city_pop,job,dob,acct_num,acct_num2,trans_num,unix_time,category,amt
0,6.760000e+11,M,Dasmarinas,"659,019 people",Chartered loss adjuster,12/12/1958,798000000000,798000000000,a72eaa86b043eed95b25bbb25b3153a1,1581314011,shopping_net,$68.88
1,3.520000e+15,M,Digos,"169,393 people","Administrator, charities/voluntary organisations",31/08/1970,968000000000,968000000000,060d12f91c13871a13963041736a4702,1590902968,entertainment,$50.06
2,4.140000e+18,M,Calapan,"133,893 people",Financial controller,23/07/1953,628000000000,628000000000,18aafb6098ab0923886c0ac83592ef8d,1585461157,food_dining,$105.44
3,4.870000e+15,M,San Fernando,"121,812 people",NaN,18/07/1964,863000000000,863000000000,45bbe714e51ab8a375454d39a190b0cb,1613063704,food_dining,$38.61
4,4.720000e+15,M,Laoag,"111,125 people",Dance movement psychotherapist,11/01/1954,257000000000,257000000000,c20ee88b451f637bc6893b7460e9fee0,1601282159,gas_transport,$82.69
...,...,...,...,...,...,...,...,...,...,...,...,...
111870,2.470000e+15,M,San Fernando,"306,659 people","Surveyor, quantity",01/11/1935,581000000000,581000000000,d44f411eabd406a76a60546e723a98fd,1628185569,kids_pets,$98.23
111871,3.520000e+15,M,Masbate,"95,389 people",Wellsite geologist,20/11/1967,531000000000,531000000000,7e767a74cae901c13f1a9d1d37aa63d4,1621481285,grocery_pos,$78.79
111872,4.620000e+15,M,San Fernando,"121,812 people",Personnel officer,20/11/1934,555000000000,555000000000,6ced184c93e66028e8d235ad3060de90,1625341374,personal_care,$31.37
111874,4.430000e+15,M,General Santos,"594,446 people",NaN,26/06/1960,319000000000,319000000000,599d3eec9b385473aa3791b620691416,1636919758,home,$74.76
111875,3.800000e+13,M,City of Isabela,"112,788 people",Sport and exercise psychologist,04/03/1967,378000000000,378000000000,67f47400873e964e10e029050dbe1fee,1605863062,shopping_pos,$3.27

# 7. Remove "$" in `amt` and convert to float
*Hint: convert to desired data type using method `.astype()`*

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 111875
Data columns (total 12 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   cc_num     100000 non-null  float64
 1   gender     100000 non-null  object
 2   city       100000 non-null  object
 3   city_pop   100000 non-null  object
 4   job        92432 non-null   object
 5   dob        100000 non-null  object
 6   acct_num   100000 non-null  int64
 7   acct_num2  100000 non-null  int64
 8   trans_num  100000 non-null  object
 9   unix_time  100000 non-null  int64
 10  category   92392 non-null   object
 11  amt        100000 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 9.9+ MB

In [ ]:
df['amt'] = df['amt'].str.replace('$', '')
df['amt'] = df['amt'].astype('float')

<ipython-input-138-923da4abe9e1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['amt'] = df['amt'].str.replace('$', '')
<ipython-input-138-923da4abe9e1>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['amt'] = df['amt'].astype('float')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 111875
Data columns (total 12 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   cc_num     100000 non-null  float64
 1   gender     100000 non-null  object
 2   city       100000 non-null  object
 3   city_pop   100000 non-null  object
 4   job        92432 non-null   object
 5   dob        100000 non-null  object
 6   acct_num   100000 non-null  int64
 7   acct_num2  100000 non-null  int64
 8   trans_num  100000 non-null  object
 9   unix_time  100000 non-null  int64
 10  category   92392 non-null   object
 11  amt        100000 non-null  float64
dtypes: float64(2), int64(3), object(7)
memory usage: 9.9+ MB

In [ ]:
df

,cc_num,gender,city,city_pop,job,dob,acct_num,acct_num2,trans_num,unix_time,category,amt
0,6.760000e+11,M,Dasmarinas,"659,019 people",Chartered loss adjuster,12/12/1958,798000000000,798000000000,a72eaa86b043eed95b25bbb25b3153a1,1581314011,shopping_net,68.88
1,3.520000e+15,M,Digos,"169,393 people","Administrator, charities/voluntary organisations",31/08/1970,968000000000,968000000000,060d12f91c13871a13963041736a4702,1590902968,entertainment,50.06
2,4.140000e+18,M,Calapan,"133,893 people",Financial controller,23/07/1953,628000000000,628000000000,18aafb6098ab0923886c0ac83592ef8d,1585461157,food_dining,105.44
3,4.870000e+15,M,San Fernando,"121,812 people",NaN,18/07/1964,863000000000,863000000000,45bbe714e51ab8a375454d39a190b0cb,1613063704,food_dining,38.61
4,4.720000e+15,M,Laoag,"111,125 people",Dance movement psychotherapist,11/01/1954,257000000000,257000000000,c20ee88b451f637bc6893b7460e9fee0,1601282159,gas_transport,82.69
...,...,...,...,...,...,...,...,...,...,...,...,...
111870,2.470000e+15,M,San Fernando,"306,659 people","Surveyor, quantity",01/11/1935,581000000000,581000000000,d44f411eabd406a76a60546e723a98fd,1628185569,kids_pets,98.23
111871,3.520000e+15,M,Masbate,"95,389 people",Wellsite geologist,20/11/1967,531000000000,531000000000,7e767a74cae901c13f1a9d1d37aa63d4,1621481285,grocery_pos,78.79
111872,4.620000e+15,M,San Fernando,"121,812 people",Personnel officer,20/11/1934,555000000000,555000000000,6ced184c93e66028e8d235ad3060de90,1625341374,personal_care,31.37
111874,4.430000e+15,M,General Santos,"594,446 people",NaN,26/06/1960,319000000000,319000000000,599d3eec9b385473aa3791b620691416,1636919758,home,74.76
111875,3.800000e+13,M,City of Isabela,"112,788 people",Sport and exercise psychologist,04/03/1967,378000000000,378000000000,67f47400873e964e10e029050dbe1fee,1605863062,shopping_pos,3.27

# 8. Remove "people" and "," in `city_pop`and convert to integer
*Hint: convert to desired data type using method `.astype()`*

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 111875
Data columns (total 12 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   cc_num     100000 non-null  float64
 1   gender     100000 non-null  object
 2   city       100000 non-null  object
 3   city_pop   100000 non-null  object
 4   job        92432 non-null   object
 5   dob        100000 non-null  object
 6   acct_num   100000 non-null  int64
 7   acct_num2  100000 non-null  int64
 8   trans_num  100000 non-null  object
 9   unix_time  100000 non-null  int64
 10  category   92392 non-null   object
 11  amt        100000 non-null  float64
dtypes: float64(2), int64(3), object(7)
memory usage: 9.9+ MB

In [ ]:
df['city_pop'] = df['city_pop'].str.replace('people','')
df['city_pop'] = df['city_pop'].str.replace(',','')

<ipython-input-143-8f83083786d1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city_pop'] = df['city_pop'].str.replace('people','')
<ipython-input-143-8f83083786d1>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city_pop'] = df['city_pop'].str.replace(',','')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 111875
Data columns (total 12 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   cc_num     100000 non-null  float64
 1   gender     100000 non-null  object
 2   city       100000 non-null  object
 3   city_pop   100000 non-null  object
 4   job        92432 non-null   object
 5   dob        100000 non-null  object
 6   acct_num   100000 non-null  int64
 7   acct_num2  100000 non-null  int64
 8   trans_num  100000 non-null  object
 9   unix_time  100000 non-null  int64
 10  category   92392 non-null   object
 11  amt        100000 non-null  float64
dtypes: float64(2), int64(3), object(7)
memory usage: 9.9+ MB

In [ ]:
df['city_pop'] = df['city_pop'].astype('int')

<ipython-input-145-c3baed35296c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city_pop'] = df['city_pop'].astype('int')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 111875
Data columns (total 12 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   cc_num     100000 non-null  float64
 1   gender     100000 non-null  object
 2   city       100000 non-null  object
 3   city_pop   100000 non-null  int64
 4   job        92432 non-null   object
 5   dob        100000 non-null  object
 6   acct_num   100000 non-null  int64
 7   acct_num2  100000 non-null  int64
 8   trans_num  100000 non-null  object
 9   unix_time  100000 non-null  int64
 10  category   92392 non-null   object
 11  amt        100000 non-null  float64
dtypes: float64(2), int64(4), object(6)
memory usage: 9.9+ MB

# **Optional, For intermediate/advanced learners**:
## Column `unix_time` is a date unique system for machines to internally tracking time. Can you convert it to a human-readable date and time in "YYYY-MM-DD HH:MM:SS" format and store in column named 'transaction_datetime`?

In [ ]:
df['transaction_datetime'] = pd.to_datetime(df['unix_time'], unit = 's')

<ipython-input-148-3ebfa96380a2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['transaction_datetime'] = pd.to_datetime(df['unix_time'], unit = 's')

In [ ]:
df['transaction_datetime'] = df['transaction_datetime'].dt.tz_convert('Asia/Shanghai')

In [ ]:
df['transaction_datetime'] = df['transaction_datetime'].dt.strftime('%Y-%m-%d %H:%M:%S')

<ipython-input-149-1e34a2d7bc17>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['transaction_datetime'] = df['transaction_datetime'].dt.strftime('%Y-%m-%d %H:%M:%S')

In [ ]:
df

,cc_num,gender,city,city_pop,job,dob,acct_num,acct_num2,trans_num,unix_time,category,amt,transaction_datetime
0,6.760000e+11,M,Dasmarinas,659019,Chartered loss adjuster,12/12/1958,798000000000,798000000000,a72eaa86b043eed95b25bbb25b3153a1,1581314011,shopping_net,68.88,2020-02-10 05:53:31
1,3.520000e+15,M,Digos,169393,"Administrator, charities/voluntary organisations",31/08/1970,968000000000,968000000000,060d12f91c13871a13963041736a4702,1590902968,entertainment,50.06,2020-05-31 05:29:28
2,4.140000e+18,M,Calapan,133893,Financial controller,23/07/1953,628000000000,628000000000,18aafb6098ab0923886c0ac83592ef8d,1585461157,food_dining,105.44,2020-03-29 05:52:37
3,4.870000e+15,M,San Fernando,121812,NaN,18/07/1964,863000000000,863000000000,45bbe714e51ab8a375454d39a190b0cb,1613063704,food_dining,38.61,2021-02-11 17:15:04
4,4.720000e+15,M,Laoag,111125,Dance movement psychotherapist,11/01/1954,257000000000,257000000000,c20ee88b451f637bc6893b7460e9fee0,1601282159,gas_transport,82.69,2020-09-28 08:35:59
...,...,...,...,...,...,...,...,...,...,...,...,...,...
111870,2.470000e+15,M,San Fernando,306659,"Surveyor, quantity",01/11/1935,581000000000,581000000000,d44f411eabd406a76a60546e723a98fd,1628185569,kids_pets,98.23,2021-08-05 17:46:09
111871,3.520000e+15,M,Masbate,95389,Wellsite geologist,20/11/1967,531000000000,531000000000,7e767a74cae901c13f1a9d1d37aa63d4,1621481285,grocery_pos,78.79,2021-05-20 03:28:05
111872,4.620000e+15,M,San Fernando,121812,Personnel officer,20/11/1934,555000000000,555000000000,6ced184c93e66028e8d235ad3060de90,1625341374,personal_care,31.37,2021-07-03 19:42:54
111874,4.430000e+15,M,General Santos,594446,NaN,26/06/1960,319000000000,319000000000,599d3eec9b385473aa3791b620691416,1636919758,home,74.76,2021-11-14 19:55:58
111875,3.800000e+13,M,City of Isabela,112788,Sport and exercise psychologist,04/03/1967,378000000000,378000000000,67f47400873e964e10e029050dbe1fee,1605863062,shopping_pos,3.27,2020-11-20 09:04:22

# 9. Save cleaned dataframe as "cc_clean.csv"

In [ ]:
df.to_csv('Data/staff_salary.csv', index = False)